/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ImportImage;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author Benten
 */
public class importImage extends javax.swing.JFrame implements MyLog {
    JLabel jlab = new JLabel(); 
    private BufferedImage img = null;
    private BufferedImage imgPrelucrata = null;
    private double[][] pozaBW = new double[1][1];
    private double[][] step2Result = new double[1][1]; // prima dimensiune este indicele coloana
    private double[][] step3Result = new double[1][1]; // prima dimensiune este indicele rand
    private Step4.Result step4Result = null;
    private JPanel rbfParamPanel = new JPanel();
    private JPanel liniarParamPanel = new JPanel();
    /**
     * Creates new form importImage
     */
    public importImage() {
        initComponents();
        rbfParamPanel.add(new JLabel("par rbf 1"));
        rbfParamPanel.add(new JLabel("par rbf 2"));
        liniarParamPanel.add(new JLabel("par liniar 1"));
        liniarParamPanel.add(new JLabel("par liniar 2"));
        rbfParamPanel.setVisible(false);
        liniarParamPanel.setVisible(false);
        
        panelParamSVM.add(rbfParamPanel);
        panelParamSVM.add(liniarParamPanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        loadImgButton = new javax.swing.JButton();
        deleteImgButton = new javax.swing.JButton();
        step1Run = new javax.swing.JButton();
        PragStep1 = new javax.swing.JLabel();
        parametru = new javax.swing.JTextField();
        saveImgStep1 = new javax.swing.JButton();
        meniuLabel = new javax.swing.JLabel();
        step2Run = new javax.swing.JButton();
        NrIteratii = new javax.swing.JLabel();
        iteratii = new javax.swing.JTextField();
        step3Run = new javax.swing.JButton();
        step4Run = new javax.swing.JButton();
        exportStep4 = new javax.swing.JButton();
        jSP = new javax.swing.JScrollPane();
        initialImgLabel = new javax.swing.JLabel();
        imgProcSP = new javax.swing.JScrollPane();
        imgProcLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelParamSVM = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadImgButton.setText("Incarca poza");
        loadImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadImgButtonActionPerformed(evt);
            }
        });

        deleteImgButton.setText("Sterge poza");
        deleteImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteImgButtonActionPerformed(evt);
            }
        });

        step1Run.setText("Generare pas 1");
        step1Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step1RunActionPerformed(evt);
            }
        });

        PragStep1.setText("Prag :");

        parametru.setText("50");
        parametru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametruActionPerformed(evt);
            }
        });

        saveImgStep1.setText("Save img");
        saveImgStep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveImgStep1ActionPerformed(evt);
            }
        });

        meniuLabel.setForeground(new java.awt.Color(0, 51, 255));
        meniuLabel.setText("Meniu");

        step2Run.setText("Generare pas 2");
        step2Run.setActionCommand("Step2");
        step2Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step2RunActionPerformed(evt);
            }
        });

        NrIteratii.setText("  Nr. Iteratii :");

        iteratii.setText("50");
        iteratii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteratiiActionPerformed(evt);
            }
        });

        step3Run.setText("Generare pas 3");
        step3Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step3RunActionPerformed(evt);
            }
        });

        step4Run.setText("Generare pas 4");
        step4Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                step4RunActionPerformed(evt);
            }
        });

        exportStep4.setText("Export train/test files");
        exportStep4.setEnabled(false);
        exportStep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportStep4ActionPerformed(evt);
            }
        });

        initialImgLabel.setForeground(new java.awt.Color(0, 51, 255));
        initialImgLabel.setText("Poza initiala");

        imgProcLabel.setForeground(new java.awt.Color(0, 51, 255));
        imgProcLabel.setText("Poza prelucrata");

        consola.setEditable(false);
        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane1.setViewportView(consola);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(step2Run, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(step1Run, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(PragStep1)
                                        .addGap(5, 5, 5)
                                        .addComponent(parametru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(saveImgStep1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(NrIteratii)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(iteratii, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(step3Run, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(step4Run, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exportStep4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(loadImgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(deleteImgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSP, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(imgProcSP, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(meniuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188)
                .addComponent(initialImgLabel)
                .addGap(265, 265, 265)
                .addComponent(imgProcLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meniuLabel)
                    .addComponent(initialImgLabel)
                    .addComponent(imgProcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadImgButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteImgButton)
                        .addGap(35, 35, 35)
                        .addComponent(step1Run)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parametru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveImgStep1)
                            .addComponent(PragStep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(step2Run)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NrIteratii, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iteratii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(step3Run)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(step4Run)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exportStep4)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSP, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(imgProcSP))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liniar", "RBF", "POLY" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParamSVMLayout = new javax.swing.GroupLayout(panelParamSVM);
        panelParamSVM.setLayout(panelParamSVMLayout);
        panelParamSVMLayout.setHorizontalGroup(
            panelParamSVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
        panelParamSVMLayout.setVerticalGroup(
            panelParamSVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(panelParamSVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(645, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelParamSVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //functie care ma ajuta sa iau o parte din imagine
    private Image ScaledImage(Image img, int w, int h) {
        BufferedImage resizeImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_BGR);
        Graphics2D g2 = resizeImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, null);
        g2.dispose();
        return resizeImage;
    }

    private void loadImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadImgButtonActionPerformed
        //create file chooser
        JFileChooser jfc = new JFileChooser();
        jfc.setSelectedFile(new File("PICT0001_croped.JPG"));
        if (jfc.showOpenDialog(loadImgButton) == JFileChooser.APPROVE_OPTION) {
            img = null;
            try {
                java.io.File f = jfc.getSelectedFile();
                img = ImageIO.read(f);
            } catch (IOException e) {
                System.out.println(e);
            }
            ImageIcon icon = new ImageIcon(ScaledImage(img, jSP.getWidth(), jSP.getHeight()));
            jlab.setIcon(icon);
            //add jLabel to scroll pane
            jSP.getViewport().add(jlab);
        }
    }//GEN-LAST:event_loadImgButtonActionPerformed

    private void deleteImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteImgButtonActionPerformed
        //remove image from jlabel jlab
        jlab.setIcon(null);
    }//GEN-LAST:event_deleteImgButtonActionPerformed

    private void step1RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step1RunActionPerformed
        int width = img.getWidth();
        int height = img.getHeight();
        imgPrelucrata = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        imgPrelucrata.setData(img.getData());
        int thresh = Integer.parseInt(parametru.getText());
        pozaBW = new double[height][width];

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                Color c = new Color(imgPrelucrata.getRGB(x, y));
                int red = c.getRed();
                int pixle = red < thresh ? 0 : 255;
                pozaBW[y][x] = red < thresh ? 0 : red == thresh ? 0.5 : 1; // poza cu prima dimensiune = randuri
                Color cnew = new Color(pixle, pixle, pixle);
                imgPrelucrata.setRGB(x, y, cnew.getRGB());
            }
        }
        ImageIcon icon = new ImageIcon(ScaledImage(imgPrelucrata, jSP.getWidth(), jSP.getHeight()));
        jlab.setIcon(icon);
        //add jLabel to scroll pane
        imgProcSP.getViewport().add(jlab);
    }//GEN-LAST:event_step1RunActionPerformed

    private void saveImgStep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveImgStep1ActionPerformed
        JFileChooser jfc = new JFileChooser();
        if (imgPrelucrata != null && jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File f = jfc.getSelectedFile();
                ImageIO.write(imgPrelucrata, "jpg", f);
            } catch (IOException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_saveImgStep1ActionPerformed

    private void parametruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parametruActionPerformed

    private void step2RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step2RunActionPerformed
        int iteratie = Integer.parseInt(iteratii.getText());
        step2Result = Step2.run(pozaBW, 1, iteratie);
        step2Result = Step2.run(step2Result, 0, 1);

        int height = step2Result.length;
        int width = step2Result[0].length;
        BufferedImage imgToSHow = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        for (int col = 0; col < width; col++) {
            for (int row = 0; row < height; row++) {
                int pixel = (int) step2Result[row][col] * 255;
                Color cnew = new Color(pixel, pixel, pixel);
                imgToSHow.setRGB(col, row, cnew.getRGB());
            }
        }

        ImageIcon icon = new ImageIcon(ScaledImage(imgToSHow, jSP.getWidth(), jSP.getHeight()));
        jlab.setIcon(icon);
        //add jLabel to scroll pane
        imgProcSP.getViewport().add(jlab);
    }//GEN-LAST:event_step2RunActionPerformed

    private void iteratiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteratiiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iteratiiActionPerformed

    private void step4RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step4RunActionPerformed
        int h = 4, l = 4;
        step4Result = Step4.run(step3Result, pozaBW, h, l);
        exportStep4.setEnabled(true);
    }//GEN-LAST:event_step4RunActionPerformed

    private void step3RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_step3RunActionPerformed
        step3Result = Step3.run(step2Result);

    }//GEN-LAST:event_step3RunActionPerformed

    private void exportStep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportStep4ActionPerformed
        double ratio = 5 / 8.0;

        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Save train file database");
        if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {

            File fTrain = jfc.getSelectedFile();
            jfc.setDialogTitle("Save test file database");
            if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                File fTest = jfc.getSelectedFile();
                saveTrainTestFile(step4Result, ratio, fTrain, fTest);
            }

        }
    }//GEN-LAST:event_exportStep4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedName = (String) jComboBox1.getSelectedItem();
        if(selectedName.equals("Liniar")){
            liniarParamPanel.setVisible(true);
            liniarParamPanel.validate();
            rbfParamPanel.setVisible(false);
        }
        this.pack();
        
        this.validate();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(importImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(importImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(importImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(importImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        importImage myFrame = new importImage();
        myFrame.setTitle("SVM");
        Utils.log = myFrame;
//        Utils.log = new ConsoleLog();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                myFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NrIteratii;
    private javax.swing.JLabel PragStep1;
    private javax.swing.JTextArea consola;
    private javax.swing.JButton deleteImgButton;
    private javax.swing.JButton exportStep4;
    private javax.swing.JLabel imgProcLabel;
    private javax.swing.JScrollPane imgProcSP;
    private javax.swing.JLabel initialImgLabel;
    private javax.swing.JTextField iteratii;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jSP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadImgButton;
    private javax.swing.JLabel meniuLabel;
    private javax.swing.JPanel panelParamSVM;
    private javax.swing.JTextField parametru;
    private javax.swing.JButton saveImgStep1;
    private javax.swing.JButton step1Run;
    private javax.swing.JButton step2Run;
    private javax.swing.JButton step3Run;
    private javax.swing.JButton step4Run;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void println(T t) {
        consola.append(t.toString() + "\n");
    }

    @Override
    public <T> void println(List<T> list) {
        consola.append("Urmeaza elemente lista:\n");
        for (T t : list) {
            consola.append(t.toString() + "\n");
        }
    }

    @Override
    public void println(double[][] d) {
        consola.append("\n\nUrmeaza elemente din matrice :\n");
        for (int row = 0; row < d.length; row++) {
            for (int col = 0; col < d[0].length; col++) {
                consola.append(d[row][col] + "  ");

            }
            consola.append("\n");
        }
    }

    private void saveTrainTestFile(Step4.Result step4Result, double ratio, File fTrain, File fTest) {
        int nrRandDinF = step4Result.F.length;
        int nrColDinF = step4Result.F[0].length;
        int N1 = (int) Math.round(ratio * nrRandDinF); //nr coloane
        double[][] labels_samples_Train = new double[N1][nrColDinF + 1];
        for (int i = 0; i < N1; i++) {
            labels_samples_Train[i][0] = step4Result.etichete[i].doubleValue();
            for (int j = 0; j < nrColDinF; j++) {
                labels_samples_Train[i][j + 1] = step4Result.F[i][j];
            }
        }
        FileUtils.writeFullInFile(fTrain.getAbsolutePath(), labels_samples_Train);

        double[][] labels_samples_Test = new double[nrRandDinF - N1][nrColDinF + 1];
        for (int i = N1; i < nrRandDinF; i++) {
            labels_samples_Test[i-N1][0] = step4Result.etichete[i].doubleValue();
            for (int j = 0; j < nrColDinF; j++) {
                labels_samples_Test[i-N1][j + 1] = step4Result.F[i][j];
            }
        }
        FileUtils.writeFullInFile(fTest.getAbsolutePath(), labels_samples_Test);

    }

}
